[pytest]
asyncio_mode = auto
testpaths = tests
python_files = test_enzyme_*.py test_sequence_*.py test_embedding_*.py test_property_*.py test_structure_*.py test_nvidia_*.py test_variant_*.py
python_classes = Test*
python_functions = test_*
log_cli = true
log_cli_level = WARNING
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
